# Generated by Django 4.2 on 2025-09-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=160)),
                ('Apellidos', models.CharField(max_length=160)),
                ('Email', models.EmailField(max_length=254)),
                ('Asunto', models.CharField(blank=True, max_length=200, null=True)),
                ('Mensaje', models.TextField()),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'db_table': 'Contactos',
            },
        ),
    ]
